### ISSUE TITLE
개발 리스트

### ISSUE THREAD

**Issue by dongx0915** [dongx0915/WePLi-Android#1]
### Todo
- [ ] UI Model 제거
- [x] MVI Orbit 추가
- [x] 바텀 네비게이션 바
- [x] Apple Music API 연동 테스트
- [ ] 대댓글
- [ ] 메인 API 캐싱
- [ ] AsyncPreview 제거
- [ ] 커스텀 스낵바 추가
